dist: bionic
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-11/run.sh |  bash
notifications:
  slack:
    secure: HB738sUPBsxVizBdZaZGDOI9gaBgTp4PjbgELJDqmBh4+CBJkHCFtTIFAIx6fwQ4cpC84igHFeL9jpLdHzfAzwpPRTPYf1jM0cZ3MA3+9VzsX20Qp2jnxxIoPP720PmkzS2LyEQsP5YZsgPqNOzp6pe+5zlel2Ru8xkH35F2SqEAAEQkG9Io1t2vmfOoL+vG+4nBAyyKpZTSHpUi3dqSMMPeTNtNs2zCMzJ0s4SZsIg8y/0eKFqdEBY5E0cQlTHMzRJK+Qnl2bmXmTLFfuGwX+tf7+Z8xJfCr1kBUa186n9HmO6LznQBdHr2p39+dAwDBDonCmr9NQIrdyELX1nINsovyA1ky/gEz7OLIHch8dg1FjSQvoIHr1i9yn9HXu0V36ALnEVY/wtIpbgwWrNSZ75K5za6ba50yAwIApDfUSS9pNCCvaSZNwYrachjCcMV8pcL3eCKDfotx0B5G3/dvsAEx+dAAWRsyG7Z4baxhqeGeq7O8sCjBS1dBseP1z0fk1cdAi/zZuh9pXCQWV8BZ+qA+V8ot9L+VTXx/2AAYnvTkXXlNZd822eaHUXxlbBsGkE0dX3dzucegNMBT8yA2q/usGdjcIGjqZPHSC0cBT3lDzle9ipziARxStJBkcRRwvccyskBasXh/asAZFUzkWKUHFD8GPOKR2ZbCdojO3k=
