- name: "Reddit App: Install mongodb"
  hosts: all
  gather_facts: yes
  become: true

  tasks:
  - name: "Import MongoDB public GPG Key"
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: 9DA31620334BD75D9DCB49F368818C72E52529D4
  - name: "Add MongoDB repository into sources list"
    apt_repository:
      repo: deb http://repo.mongodb.org/apt/ubuntu {{ansible_distribution_release}}/mongodb-org/4.0 multiverse
      state: present
  - name: "Install MongoDB package"
    apt:
      name: mongodb-org
      state: present
      update_cache: yes


# Deploy reddit app
- name: "Reddit App: Deploy application"
  hosts: reddit_app
  gather_facts: no

  tasks:
  - name: Remove me after adding real things
    debug:
      msg: "В этом сценарии нужно добавить модули для деплоя приложения, после можно удалить вызов модуля debug, который выводит это сообщение"
